### ISSUE TITLE
Suppress a lint warning about shared prefs editor

### ISSUE THREAD

**Issue by caarmen** [BoD/android-prefs#11]
Add a suppression for the `CommitPrefEdits` lint check, in the generated method that wraps a shared pefs editor.
<img width="832" alt="prefs" src="https://cloud.githubusercontent.com/assets/1731388/18414003/da54607e-77ba-11e6-8e8a-06ea2894821b.png">

**Comment by BoD** [comment]
Resolved in 1.1.0.
