### ISSUE TITLE
Function: Replace Prefs in <YourClassName>Prefs with a different characters

### ISSUE THREAD

**Issue by sonvp** [BoD/android-prefs#13]
Hi @BoD . You can update function replace Prefs in `<YourClassName>Prefs` with a different characters
Ex: `<YourClassName>Prefs  ---> <YourClassName>Helper.`

**Comment by BoD** [comment]
Hi! 
I am sorry, I do not understand what you are asking.

**Comment by sonvp** [comment]
hi @BoD 
I have class name School {}
When i using your libs --> class will auto generate name SchoolPrefs.. But i want "Prefs" is another words by me: example SchoolHelper instead of SchoolPrefs. 
Thank you.

**Comment by tommus** [comment]
So, basically you would like to use a different suffix for generated classes, am I correct?

**Comment by BoD** [comment]
I mean this could be configurable somehow, but that would be to the detriment of the general simplicity of this lib. Since there is very low demand for this currently, I'm going to close this for now.
