### ISSUE TITLE
Unboxing of mainPrefs.getBooleanValue() may produce "NullPointerException"

### ISSUE THREAD

**Issue by akbarsha03** [BoD/android-prefs#4]
When I use the **Boolean** type in my **MainPrefs** class Android Studio gives me the following probable bug with a warning

Unboxing of mainPrefs.getBooleanValue() may produce "java.lang.NullPointerException"

How should I make sure it won't produce any **NullPointerException**

![screenshot 2015-08-19 15 03 38](https://cloud.githubusercontent.com/assets/4894571/9353132/b646652e-4683-11e5-8eca-09297e9e5995.png)

**Comment by BoD** [comment]
Put a default value on your property (for instance @DefaultBoolean(false)).

**Comment by akbarsha03** [comment]
@BoD Thank you this resolved the issue :+1:
